name: veracode-scan

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  pull-requests: write
  contents: read

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v3

      - name: set-up-jdk-17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: build-project
        run: ./mvnw clean package -DskipTests

      - name: scan-with-veracode
        id: veracode
        uses: veracode/veracode-uploadandscan-action@v1.0.9
        with:
          appname: 'SensorPulse'
          filepath: 'target/sensor-pulse.jar'
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          createprofile: true
          criticality: 'High'
          scanpolling: true
          scansummary: true
          failbuild: false

      - name: comment-on-pr
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            **Veracode Analysis**
            - App: `SensorPulse`
            - Scan completed and uploaded
            - [View full scan results in Veracode](https://analysiscenter.veracode.com/)
